### ISSUE TITLE
matches_pattern/pat generates error: cannot find macro `matches_pattern_internal` in this scope

### ISSUE THREAD

**Issue by Aetf** [google/googletest-rust#86]
They were working fine in the 0.3 release, but are broken in 0.4

To reproduce:
```
#[cfg(test)]
mod tests {
    use googletest::{expect_that, google_test, Result, pat, matches_pattern};

    #[google_test]
    fn this_runs_twice() -> Result<()> {
        expect_that!(42, pat!(42));
        Ok(())
    }
}
```

With a minimal `Cargo.toml`
```
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
googletest = "0.4.0"
```

**Comment by hovinen** [comment]
Thank you for reporting this! My apologies for allowing this to slip by in the latest release.

I've pushed a new branch `fix-matches-pattern` with a fix for the problem. I'll make sure we push a new release with the fix as soon as possible.
